[package]
name = "sg-tba"
authors = [ "Kromsten <s@noreply.megarock.labs>" ]
edition     = { workspace = true }
version     = { workspace = true }
repository  = { workspace = true }
description = "Definition and types for Stargaze Token-Bound Accounts"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
schemars        = { workspace = true }

cw82            = { workspace = true }
cw83            = { workspace = true }

cw721           = { workspace = true }
sg-std          = { workspace = true }
sg721-base      = { workspace = true, features = ["library"] }
